/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("block-palette-icons", manifest);
runner.l10n(l10n);
runner.userstyle("userstyle.css", () => require("!!raw-loader!./userstyle.css"));
runner.run();
