/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("tw-project-info", manifest);
runner.l10n(l10n);
runner.userscript("blockcount.js", () => require("./blockcount.js"));
runner.run();
