/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("data-category-tweaks-v2", manifest);
runner.l10n(l10n);
runner.userscript("userscript.js", () => require("./userscript.js"));
runner.run();
