/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("editor-theme3", manifest);
runner.l10n(l10n);
runner.userscript("theme3.js", () => require("./theme3.js"));
runner.userstyle("theme3.css", () => require("!!raw-loader!./theme3.css"));
runner.run();
