/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("tw-interface-customization", manifest);
runner.l10n(l10n);
runner.userscript("remove-backpack.js", () => require("./remove-backpack.js"));
runner.userscript("remove-warning.js", () => require("./remove-warning.js"));
runner.userstyle("remove-backpack.css", () => require("!!raw-loader!./remove-backpack.css"));
runner.run();
