/* generated by pull.js */
export default {
  "de": () => require("./l10n/de.json"),
  "en": () => require("./l10n/en.json"),
  "es": () => require("./l10n/es.json"),
  "fr": () => require("./l10n/fr.json"),
  "it": () => require("./l10n/it.json"),
  "ja": () => require("./l10n/ja.json"),
  "ko": () => require("./l10n/ko.json"),
  "pl": () => require("./l10n/pl.json"),
  "pt-br": () => require("./l10n/pt-br.json"),
  "ro": () => require("./l10n/ro.json"),
  "ru": () => require("./l10n/ru.json"),
  "sl": () => require("./l10n/sl.json"),
  "sv": () => require("./l10n/sv.json"),
  "tr": () => require("./l10n/tr.json"),
};
