/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("remove-curved-stage-border", manifest);
runner.l10n(l10n);
runner.userstyle("remove-borders.css", () => require("!!raw-loader!./remove-borders.css"));
runner.run();
