/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("gamepad", manifest);
runner.l10n(l10n);
runner.userscript("userscript.js", () => require("./userscript.js"));
runner.userstyle("style.css", () => require("!!raw-loader!./style.css"));
runner.userstyle("gamepadlib.css", () => require("!!raw-loader!./gamepadlib.css"));
runner.run();
