/* generated by pull.js */
import AddonRunner from "../../api.js";
import manifest from "./addon.json";
import l10n from "./l10n.js";
const runner = new AddonRunner("editor-stage-left", manifest);
runner.l10n(l10n);
runner.userscript("fix-share-the-love.js", () => require("./fix-share-the-love.js"));
runner.userstyle("stageleft.css", () => require("!!raw-loader!./stageleft.css"));
runner.run();
